FROM python:3.12-slim

WORKDIR /app

COPY discord/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY moderation/ /app/moderation/
COPY discord/ /app/discord_bot/

CMD ["python", "-m", "discord_bot.main"]
